author = "Mochamad Boval"
baseURL = "https://boval.my.id/"
languageCode = "id"
paginate = 10
theme = "paper"
title = "Boval"

[[menu.main]]
identifier = "portofolio"
name = "Portofolio"
url = "/portofolio"
[[menu.main]]
identifier = "profil"
name = "Profil"
url = "/profil"
